name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run check

      - name: Build
        run: npm run build

      - name: Database push (skipped if no DATABASE_URL)
        if: ${{ env.DATABASE_URL != '' }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run db:push

      - name: Package artifact
        if: github.event_name == 'push'
        run: |
          tar -czf build-artifact.tgz dist/
        shell: bash

      - name: Upload artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-artifact.tgz



